version: "3.7"

services:
  web:
    container_name: "web"
    image: nginx:latest
    depends_on:
      - app
    ports:
      - "8084:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./etc/letsencrypt/live/1075711-cc91283.tmweb.ru/fullchain.pem:/etc/letsencrypt/live/1075711-cc91283.tmweb.ru/fullchain.pem
      - ./etc/letsencrypt/live/1075711-cc91283.tmweb.ru/privkey.pem:/etc/letsencrypt/live/1075711-cc91283.tmweb.ru/privkey.pem

  app:
    container_name: "app"
    image: airat696/webtools:0.8
    depends_on:
      - database
#    restart: always
    build:
      context: . #на каком уровне находится Dockerfile
      dockerfile: Dockerfile
    ports:
      - "8000:8000"

  database:
    container_name: "database"
    image: postgres
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/
    restart: always
    ports:
      - "5432:5432"

volumes:
  postgres_data:
