version: "3.7"

services:
  web:
    container_name: "web"
    image: nginx:latest
    depends_on:
      - app
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./etc/letsencrypt/live/1075711-cc91283.tmweb.ru/fullchain.pem:/etc/letsencrypt/live/1075711-cc91283.tmweb.ru/fullchain.pem
      - ./etc/letsencrypt/live/1075711-cc91283.tmweb.ru/privkey.pem:/etc/letsencrypt/live/1075711-cc91283.tmweb.ru/privkey.pem

#  certbot:
#    container_name: "certbot"
#    image: certbot/certbot:latest
#    volumes:
#      - ./certbot/www/:/var/www/certbot/:rw
#      - ./certbot/conf/:/etc/letsencrypt/:rw

  app:
    container_name: "app"
    image: airat696/webtools:0.8
    depends_on:
      - database
#    restart: always
    build:
      context: . #на каком уровне находится Dockerfile
      dockerfile: Dockerfile
    ports:
      - "8000:8000"

  database:
    container_name: "database"
    image: postgres
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/
    restart: always
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "jx8BOg2010"
      POSTGRES_DB: "tools_links_db"
      POSTGRES_HOST: "database"
#      PGDATA: /home/ubuntu/postgres/data
#      POSTGRES_INITDB_ARGS: "-A md5"
#      - database.env #конфигурация доступов для бд
    ports:
      - "5432:5432"

volumes:
  postgres_data: